language: python
python:
- '3.10'
install:
- pip install -r requirements.txt
script:
- pytest -vv --cov=./ --cov-report=xml tests/
- codecov
deploy:
  provider: pypi
  username: __token__
  password:
    secure: <TOKEN>
  on:
    tags: true
    branch: master